name: CI

on: push

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Fetch dependencies
      run: cargo fetch
    - name: Build in release mode
      run: cargo build --release --frozen
  
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Make mask available for certain test suites that depend on it
      run: export PATH="$PATH:./target/debug"
    - name: Test echo PATH
      run: echo $PATH
    - name: Fetch dependencies
      run: cargo fetch
    - name: Build in test mode
      run: cargo build --tests --frozen
    - name: Run tests
      run: cargo test --frozen
  
  format:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Verify formatting is correct
      run: cargo fmt --all -- --check
