name: CI

on: push

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Fetch dependencies
      run: cargo fetch
    - name: Build in release mode
      run: cargo build --release --frozen
  
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Make mask available for certain test suites that depend on it
      run: pwd && ls -al #export PATH="$PATH:~/repo/target/debug"
    - name: Fetch dependencies
      run: cargo fetch
    - name: Build in debug mode
      run: cargo build --frozen
    - name: Run tests
      run: cargo test --verbose --frozen
  
  format:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Verify formatting is correct
      run: cargo fmt --all -- --check
