name: New Release

on:
  release:
    types: [created]

jobs:
  release-linux:
    name: Build and attach x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Fetch dependencies
        run: cargo fetch
      - name: Build in release mode
        run: cargo build --release --frozen --target x86_64-unknown-linux-gnu
      - name: Add the version tag to the binary name
        run: |
          VERSION_TAG=$(jq --raw-output '.release.tag_name' "$GITHUB_EVENT_PATH")
          echo "VERSION_TAG is $VERSION_TAG"
          mkdir assets
          mv ./target/x86_64-unknown-linux-gnu/release/mask ./assets/mask-${VERSION_TAG}-x86_64-unknown-linux-gnu
      - name: Attach the binary to the release
        uses: ./.github/actions/attach-release-assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          assets: assets/*
